# Generated by Django 5.0.3 on 2024-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_home_slider_alter_campaign_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_slider',
            name='image',
            field=models.ImageField(upload_to='slider_images'),
        ),
    ]
