# Generated by Django 5.0.3 on 2024-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_home_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deal_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
