# Generated by Django 5.0.3 on 2024-03-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_campaign_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
