# Generated by Django 5.0.3 on 2024-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
