# Generated by Django 5.0.3 on 2024-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_product_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='view_size',
            field=models.CharField(blank=True, help_text='Size in width × height format', max_length=50, null=True),
        ),
    ]
