# Generated by Django 5.0.3 on 2024-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_remove_product_screen_size_remove_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in kilograms', max_digits=5),
            preserve_default=False,
        ),
    ]
