# Generated by Django 5.0.3 on 2024-03-15 19:36

import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=info.models.get_default_end_date),
        ),
    ]
